using  System;
using  System.Collections.Generic;
using  System.Linq.Expressions;
using  System.Web;
using  Umbraco.Core.Models;
using  Umbraco.Core.Models.PublishedContent;
using  Umbraco.Web;
using  Umbraco.ModelsBuilder;
using  Umbraco.ModelsBuilder.Umbraco;
[assembly: PureLiveAssembly]
[assembly:ModelsBuilderAssembly(PureLive = true, SourceHash = "a7337d011545a37b")]
[assembly:System.Reflection.AssemblyVersion("0.0.0.1")]


// FILE: models.generated.cs

//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------















namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Homepage</summary>
	[PublishedContentModel("homepage")]
	public partial class Homepage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homepage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Homepage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Homepage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Home Grid: The paragraph under the hero image.
		///</summary>
		[ImplementPropertyType("homeGrid")]
		public Newtonsoft.Json.Linq.JToken HomeGrid
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("homeGrid"); }
		}

		///<summary>
		/// Main Phone Number: This is the local phone number to be displayed sitewide.
		///</summary>
		[ImplementPropertyType("mainPhoneNumber")]
		public string MainPhoneNumber
		{
			get { return this.GetPropertyValue<string>("mainPhoneNumber"); }
		}

		///<summary>
		/// Page Name: The name people will see in the browser tab.
		///</summary>
		[ImplementPropertyType("pageName")]
		public string PageName
		{
			get { return this.GetPropertyValue<string>("pageName"); }
		}

		///<summary>
		/// Site Logo
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public string SiteLogo
		{
			get { return this.GetPropertyValue<string>("siteLogo"); }
		}

		///<summary>
		/// Site Logo Width
		///</summary>
		[ImplementPropertyType("siteLogoWidth")]
		public string SiteLogoWidth
		{
			get { return this.GetPropertyValue<string>("siteLogoWidth"); }
		}
	}

	/// <summary>Category</summary>
	[PublishedContentModel("category")]
	public partial class Category : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "category";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Category(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Category, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Page</summary>
	[PublishedContentModel("page")]
	public partial class Page : Category
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "page";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Page(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Page, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Alternate URL: This is where the page will link to if you don't want it to go to a page on our site.
		///</summary>
		[ImplementPropertyType("alternatePageLink")]
		public string AlternatePageLink
		{
			get { return this.GetPropertyValue<string>("alternatePageLink"); }
		}

		///<summary>
		/// Navigation Description
		///</summary>
		[ImplementPropertyType("navigationDesc")]
		public string NavigationDesc
		{
			get { return this.GetPropertyValue<string>("navigationDesc"); }
		}

		///<summary>
		/// Navigation Label: This is the main navigation label
		///</summary>
		[ImplementPropertyType("navigationLabel")]
		public string NavigationLabel
		{
			get { return this.GetPropertyValue<string>("navigationLabel"); }
		}

		///<summary>
		/// Page Grid
		///</summary>
		[ImplementPropertyType("pageGrid")]
		public Newtonsoft.Json.Linq.JToken PageGrid
		{
			get { return this.GetPropertyValue<Newtonsoft.Json.Linq.JToken>("pageGrid"); }
		}

		///<summary>
		/// Hide from navigation
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("umbracoNaviHide"); }
		}
	}

	/// <summary>Page With Hero</summary>
	[PublishedContentModel("pageWithHero")]
	public partial class PageWithHero : Category
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "pageWithHero";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public PageWithHero(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<PageWithHero, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Content
		///</summary>
		[ImplementPropertyType("content")]
		public string Content
		{
			get { return this.GetPropertyValue<string>("content"); }
		}

		///<summary>
		/// Hero
		///</summary>
		[ImplementPropertyType("hero")]
		public string Hero
		{
			get { return this.GetPropertyValue<string>("hero"); }
		}
	}

	/// <summary>Master</summary>
	[PublishedContentModel("master")]
	public partial class Master : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "master";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Master(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Master, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Site Logo
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public string SiteLogo
		{
			get { return this.GetPropertyValue<string>("siteLogo"); }
		}

		///<summary>
		/// Site Logo Width
		///</summary>
		[ImplementPropertyType("siteLogoWidth")]
		public int SiteLogoWidth
		{
			get { return this.GetPropertyValue<int>("siteLogoWidth"); }
		}
	}

	/// <summary>Location Type</summary>
	[PublishedContentModel("locationType1")]
	public partial class LocationType1 : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "locationType1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public LocationType1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<LocationType1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Location</summary>
	[PublishedContentModel("location")]
	public partial class Location : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "location";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Location(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Location, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("address"); }
		}

		///<summary>
		/// Ambulatory Surgery Center Description
		///</summary>
		[ImplementPropertyType("ambulatorySurgeryCenterDescription")]
		public string AmbulatorySurgeryCenterDescription
		{
			get { return this.GetPropertyValue<string>("ambulatorySurgeryCenterDescription"); }
		}

		///<summary>
		/// Business Hours
		///</summary>
		[ImplementPropertyType("businessHours")]
		public IEnumerable<string> BusinessHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("businessHours"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		///<summary>
		/// Comfort and Recovery Suites Description
		///</summary>
		[ImplementPropertyType("comfortAndRecoverySuitesDescription")]
		public string ComfortAndRecoverySuitesDescription
		{
			get { return this.GetPropertyValue<string>("comfortAndRecoverySuitesDescription"); }
		}

		///<summary>
		/// Display Name: The name that will be used at the top of the page and an alternative to the alias made upon creation.
		///</summary>
		[ImplementPropertyType("displayName")]
		public string DisplayName
		{
			get { return this.GetPropertyValue<string>("displayName"); }
		}

		///<summary>
		/// Fax Number
		///</summary>
		[ImplementPropertyType("faxNumber")]
		public string FaxNumber
		{
			get { return this.GetPropertyValue<string>("faxNumber"); }
		}

		///<summary>
		/// Holiday Hours
		///</summary>
		[ImplementPropertyType("holidayHours")]
		public IEnumerable<string> HolidayHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("holidayHours"); }
		}

		///<summary>
		/// Imaging Center Description
		///</summary>
		[ImplementPropertyType("imagingCenterDescription")]
		public string ImagingCenterDescription
		{
			get { return this.GetPropertyValue<string>("imagingCenterDescription"); }
		}

		///<summary>
		/// Location Photo: The primary photo on the top of the location page content section.
		///</summary>
		[ImplementPropertyType("locationPhoto")]
		public string LocationPhoto
		{
			get { return this.GetPropertyValue<string>("locationPhoto"); }
		}

		///<summary>
		/// Location General Description: The brief location description located right underneath the location display name.
		///</summary>
		[ImplementPropertyType("locationTitleDescription")]
		public string LocationTitleDescription
		{
			get { return this.GetPropertyValue<string>("locationTitleDescription"); }
		}

		///<summary>
		/// Location Types
		///</summary>
		[ImplementPropertyType("locationTypes")]
		public IEnumerable<string> LocationTypes
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("locationTypes"); }
		}

		///<summary>
		/// Map File Upload
		///</summary>
		[ImplementPropertyType("mapFileUpload")]
		public IEnumerable<IPublishedContent> MapFileUpload
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("mapFileUpload"); }
		}

		///<summary>
		/// MRI Description
		///</summary>
		[ImplementPropertyType("mriDescription")]
		public string MriDescription
		{
			get { return this.GetPropertyValue<string>("mriDescription"); }
		}

		///<summary>
		/// Optical Description
		///</summary>
		[ImplementPropertyType("opticalDescription")]
		public string OpticalDescription
		{
			get { return this.GetPropertyValue<string>("opticalDescription"); }
		}

		///<summary>
		/// Optical Hours
		///</summary>
		[ImplementPropertyType("opticalHours")]
		public IEnumerable<string> OpticalHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("opticalHours"); }
		}

		///<summary>
		/// Pharmacy Description
		///</summary>
		[ImplementPropertyType("pharmacyDescription")]
		public string PharmacyDescription
		{
			get { return this.GetPropertyValue<string>("pharmacyDescription"); }
		}

		///<summary>
		/// Pharmacy Hours
		///</summary>
		[ImplementPropertyType("pharmacyHours")]
		public IEnumerable<string> PharmacyHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("pharmacyHours"); }
		}

		///<summary>
		/// Phone Number
		///</summary>
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber
		{
			get { return this.GetPropertyValue<string>("phoneNumber"); }
		}

		///<summary>
		/// Same Day Appointment Number
		///</summary>
		[ImplementPropertyType("sameDayAppointmentNumber")]
		public string SameDayAppointmentNumber
		{
			get { return this.GetPropertyValue<string>("sameDayAppointmentNumber"); }
		}

		///<summary>
		/// Services List: This is a bullet list of services to be displayed on the location page.
		///</summary>
		[ImplementPropertyType("servicesList")]
		public IEnumerable<string> ServicesList
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("servicesList"); }
		}

		///<summary>
		/// Toll Free Phone Number
		///</summary>
		[ImplementPropertyType("tollFreePhoneNumber")]
		public string TollFreePhoneNumber
		{
			get { return this.GetPropertyValue<string>("tollFreePhoneNumber"); }
		}

		///<summary>
		/// Hide from navigation
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("umbracoNaviHide"); }
		}

		///<summary>
		/// Urgent Care Description
		///</summary>
		[ImplementPropertyType("urgentCareDescription")]
		public string UrgentCareDescription
		{
			get { return this.GetPropertyValue<string>("urgentCareDescription"); }
		}

		///<summary>
		/// Urgent Care Hours
		///</summary>
		[ImplementPropertyType("urgentCareHours")]
		public IEnumerable<string> UrgentCareHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("urgentCareHours"); }
		}

		///<summary>
		/// Zip Code
		///</summary>
		[ImplementPropertyType("zipCode")]
		public string ZipCode
		{
			get { return this.GetPropertyValue<string>("zipCode"); }
		}
	}

	/// <summary>Provider Type</summary>
	[PublishedContentModel("providerType")]
	public partial class ProviderType : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "providerType";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public ProviderType(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<ProviderType, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Available at locations
		///</summary>
		[ImplementPropertyType("availableAtLocations")]
		public IEnumerable<string> AvailableAtLocations
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("availableAtLocations"); }
		}

		///<summary>
		/// Specialty
		///</summary>
		[ImplementPropertyType("specialty")]
		public string Specialty
		{
			get { return this.GetPropertyValue<string>("specialty"); }
		}

		///<summary>
		/// Hide from navigation
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("umbracoNaviHide"); }
		}
	}

	/// <summary>Provider</summary>
	[PublishedContentModel("provider")]
	public partial class Provider : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "provider";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Provider(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Provider, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Academic Appointments
		///</summary>
		[ImplementPropertyType("academicAppointments")]
		public string AcademicAppointments
		{
			get { return this.GetPropertyValue<string>("academicAppointments"); }
		}

		///<summary>
		/// Additional Procedures
		///</summary>
		[ImplementPropertyType("additionalProcedures")]
		public string AdditionalProcedures
		{
			get { return this.GetPropertyValue<string>("additionalProcedures"); }
		}

		///<summary>
		/// Also Sees Patients At
		///</summary>
		[ImplementPropertyType("alsoSeesPatientsAt")]
		public IEnumerable<string> AlsoSeesPatientsAt
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("alsoSeesPatientsAt"); }
		}

		///<summary>
		/// Bio
		///</summary>
		[ImplementPropertyType("bio")]
		public string Bio
		{
			get { return this.GetPropertyValue<string>("bio"); }
		}

		///<summary>
		/// Board Certifications
		///</summary>
		[ImplementPropertyType("boardCertifications")]
		public string BoardCertifications
		{
			get { return this.GetPropertyValue<string>("boardCertifications"); }
		}

		///<summary>
		/// DX Codes
		///</summary>
		[ImplementPropertyType("dXCodes")]
		public string DXcodes
		{
			get { return this.GetPropertyValue<string>("dXCodes"); }
		}

		///<summary>
		/// Fellowship
		///</summary>
		[ImplementPropertyType("fellowship")]
		public string Fellowship
		{
			get { return this.GetPropertyValue<string>("fellowship"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public string Image
		{
			get { return this.GetPropertyValue<string>("image"); }
		}

		///<summary>
		/// Internship
		///</summary>
		[ImplementPropertyType("internship")]
		public string Internship
		{
			get { return this.GetPropertyValue<string>("internship"); }
		}

		///<summary>
		/// Main Location
		///</summary>
		[ImplementPropertyType("mainLocation")]
		public string MainLocation
		{
			get { return this.GetPropertyValue<string>("mainLocation"); }
		}

		///<summary>
		/// Medical School
		///</summary>
		[ImplementPropertyType("medicalSchool")]
		public string MedicalSchool
		{
			get { return this.GetPropertyValue<string>("medicalSchool"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public string Phone
		{
			get { return this.GetPropertyValue<string>("phone"); }
		}

		///<summary>
		/// Professional Societies
		///</summary>
		[ImplementPropertyType("professionalSocieties")]
		public string ProfessionalSocieties
		{
			get { return this.GetPropertyValue<string>("professionalSocieties"); }
		}

		///<summary>
		/// Quote
		///</summary>
		[ImplementPropertyType("quote")]
		public string Quote
		{
			get { return this.GetPropertyValue<string>("quote"); }
		}

		///<summary>
		/// Rating ID
		///</summary>
		[ImplementPropertyType("ratingID")]
		public string RatingID
		{
			get { return this.GetPropertyValue<string>("ratingID"); }
		}

		///<summary>
		/// Residency
		///</summary>
		[ImplementPropertyType("residency")]
		public string Residency
		{
			get { return this.GetPropertyValue<string>("residency"); }
		}

		///<summary>
		/// Specialties
		///</summary>
		[ImplementPropertyType("specialties")]
		public IEnumerable<string> Specialties
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("specialties"); }
		}

		///<summary>
		/// State Licenses
		///</summary>
		[ImplementPropertyType("stateLicenses")]
		public string StateLicenses
		{
			get { return this.GetPropertyValue<string>("stateLicenses"); }
		}

		///<summary>
		/// Synonyms
		///</summary>
		[ImplementPropertyType("synonyms")]
		public string Synonyms
		{
			get { return this.GetPropertyValue<string>("synonyms"); }
		}
	}

	/// <summary>Search</summary>
	[PublishedContentModel("search")]
	public partial class Search : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "search";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Search(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Search, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}
	}

	/// <summary>Folder</summary>
	[PublishedContentModel("Folder")]
	public partial class Folder : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Folder";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Folder(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Folder, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Contents:
		///</summary>
		[ImplementPropertyType("contents")]
		public object Contents
		{
			get { return this.GetPropertyValue("contents"); }
		}
	}

	/// <summary>Image</summary>
	[PublishedContentModel("Image")]
	public partial class Image : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Image";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public Image(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Image, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Text Label
		///</summary>
		[ImplementPropertyType("textLabel")]
		public string TextLabel
		{
			get { return this.GetPropertyValue<string>("textLabel"); }
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload image
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public Umbraco.Web.Models.ImageCropDataSet UmbracoFile
		{
			get { return this.GetPropertyValue<Umbraco.Web.Models.ImageCropDataSet>("umbracoFile"); }
		}

		///<summary>
		/// Height
		///</summary>
		[ImplementPropertyType("umbracoHeight")]
		public string UmbracoHeight
		{
			get { return this.GetPropertyValue<string>("umbracoHeight"); }
		}

		///<summary>
		/// Width
		///</summary>
		[ImplementPropertyType("umbracoWidth")]
		public string UmbracoWidth
		{
			get { return this.GetPropertyValue<string>("umbracoWidth"); }
		}
	}

	/// <summary>File</summary>
	[PublishedContentModel("File")]
	public partial class File : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "File";
		public new const PublishedItemType ModelItemType = PublishedItemType.Media;
#pragma warning restore 0109

		public File(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<File, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Text Label: The label that will show as a link.
		///</summary>
		[ImplementPropertyType("textLabel")]
		public string TextLabel
		{
			get { return this.GetPropertyValue<string>("textLabel"); }
		}

		///<summary>
		/// Size
		///</summary>
		[ImplementPropertyType("umbracoBytes")]
		public string UmbracoBytes
		{
			get { return this.GetPropertyValue<string>("umbracoBytes"); }
		}

		///<summary>
		/// Type
		///</summary>
		[ImplementPropertyType("umbracoExtension")]
		public string UmbracoExtension
		{
			get { return this.GetPropertyValue<string>("umbracoExtension"); }
		}

		///<summary>
		/// Upload file
		///</summary>
		[ImplementPropertyType("umbracoFile")]
		public string UmbracoFile
		{
			get { return this.GetPropertyValue<string>("umbracoFile"); }
		}
	}

	/// <summary>Member</summary>
	[PublishedContentModel("Member")]
	public partial class Member : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "Member";
		public new const PublishedItemType ModelItemType = PublishedItemType.Member;
#pragma warning restore 0109

		public Member(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Member, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Is Approved
		///</summary>
		[ImplementPropertyType("umbracoMemberApproved")]
		public bool UmbracoMemberApproved
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberApproved"); }
		}

		///<summary>
		/// Comments
		///</summary>
		[ImplementPropertyType("umbracoMemberComments")]
		public string UmbracoMemberComments
		{
			get { return this.GetPropertyValue<string>("umbracoMemberComments"); }
		}

		///<summary>
		/// Failed Password Attempts
		///</summary>
		[ImplementPropertyType("umbracoMemberFailedPasswordAttempts")]
		public string UmbracoMemberFailedPasswordAttempts
		{
			get { return this.GetPropertyValue<string>("umbracoMemberFailedPasswordAttempts"); }
		}

		///<summary>
		/// Last Lockout Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLockoutDate")]
		public string UmbracoMemberLastLockoutDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLockoutDate"); }
		}

		///<summary>
		/// Last Login Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastLogin")]
		public string UmbracoMemberLastLogin
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastLogin"); }
		}

		///<summary>
		/// Last Password Change Date
		///</summary>
		[ImplementPropertyType("umbracoMemberLastPasswordChangeDate")]
		public string UmbracoMemberLastPasswordChangeDate
		{
			get { return this.GetPropertyValue<string>("umbracoMemberLastPasswordChangeDate"); }
		}

		///<summary>
		/// Is Locked Out
		///</summary>
		[ImplementPropertyType("umbracoMemberLockedOut")]
		public bool UmbracoMemberLockedOut
		{
			get { return this.GetPropertyValue<bool>("umbracoMemberLockedOut"); }
		}

		///<summary>
		/// Password Answer
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalAnswer")]
		public string UmbracoMemberPasswordRetrievalAnswer
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalAnswer"); }
		}

		///<summary>
		/// Password Question
		///</summary>
		[ImplementPropertyType("umbracoMemberPasswordRetrievalQuestion")]
		public string UmbracoMemberPasswordRetrievalQuestion
		{
			get { return this.GetPropertyValue<string>("umbracoMemberPasswordRetrievalQuestion"); }
		}
	}

}



// EOF
