//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Homepage</summary>
	[PublishedContentModel("homepage")]
	public partial class Homepage : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "homepage";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Homepage(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Homepage, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Hero Image: This is the big image on the top of the page.
		///</summary>
		[ImplementPropertyType("heroImage")]
		public string HeroImage
		{
			get { return this.GetPropertyValue<string>("heroImage"); }
		}

		///<summary>
		/// Main Copy: The paragraph under the hero image.
		///</summary>
		[ImplementPropertyType("mainCopy")]
		public string MainCopy
		{
			get { return this.GetPropertyValue<string>("mainCopy"); }
		}

		///<summary>
		/// Main Phone Number: This is the local phone number to be displayed sitewide.
		///</summary>
		[ImplementPropertyType("mainPhoneNumber")]
		public string MainPhoneNumber
		{
			get { return this.GetPropertyValue<string>("mainPhoneNumber"); }
		}

		///<summary>
		/// Page Name: The name people will see in the browser tab.
		///</summary>
		[ImplementPropertyType("pageName")]
		public string PageName
		{
			get { return this.GetPropertyValue<string>("pageName"); }
		}

		///<summary>
		/// Section 1 Title
		///</summary>
		[ImplementPropertyType("section1Title")]
		public string Section1Title
		{
			get { return this.GetPropertyValue<string>("section1Title"); }
		}

		///<summary>
		/// Site Logo
		///</summary>
		[ImplementPropertyType("siteLogo")]
		public string SiteLogo
		{
			get { return this.GetPropertyValue<string>("siteLogo"); }
		}

		///<summary>
		/// Site Logo Width
		///</summary>
		[ImplementPropertyType("siteLogoWidth")]
		public string SiteLogoWidth
		{
			get { return this.GetPropertyValue<string>("siteLogoWidth"); }
		}
	}
}
