//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Location</summary>
	[PublishedContentModel("location1")]
	public partial class Location1 : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "location1";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Location1(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Location1, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Address
		///</summary>
		[ImplementPropertyType("address")]
		public string Address
		{
			get { return this.GetPropertyValue<string>("address"); }
		}

		///<summary>
		/// Ambulatory Surgery Center Description
		///</summary>
		[ImplementPropertyType("ambulatorySurgeryCenterDescription")]
		public string AmbulatorySurgeryCenterDescription
		{
			get { return this.GetPropertyValue<string>("ambulatorySurgeryCenterDescription"); }
		}

		///<summary>
		/// Business Hours
		///</summary>
		[ImplementPropertyType("businessHours")]
		public IEnumerable<string> BusinessHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("businessHours"); }
		}

		///<summary>
		/// City
		///</summary>
		[ImplementPropertyType("city")]
		public string City
		{
			get { return this.GetPropertyValue<string>("city"); }
		}

		///<summary>
		/// Comfort and Recovery Suites Description
		///</summary>
		[ImplementPropertyType("comfortAndRecoverySuitesDescription")]
		public string ComfortAndRecoverySuitesDescription
		{
			get { return this.GetPropertyValue<string>("comfortAndRecoverySuitesDescription"); }
		}

		///<summary>
		/// Display Name: The name that will be used at the top of the page and an alternative to the alias made upon creation.
		///</summary>
		[ImplementPropertyType("displayName")]
		public string DisplayName
		{
			get { return this.GetPropertyValue<string>("displayName"); }
		}

		///<summary>
		/// Fax Number
		///</summary>
		[ImplementPropertyType("faxNumber")]
		public string FaxNumber
		{
			get { return this.GetPropertyValue<string>("faxNumber"); }
		}

		///<summary>
		/// Holiday Hours
		///</summary>
		[ImplementPropertyType("holidayHours")]
		public IEnumerable<string> HolidayHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("holidayHours"); }
		}

		///<summary>
		/// Imaging Center Description
		///</summary>
		[ImplementPropertyType("imagingCenterDescription")]
		public string ImagingCenterDescription
		{
			get { return this.GetPropertyValue<string>("imagingCenterDescription"); }
		}

		///<summary>
		/// Location Photo: The primary photo on the top of the location page content section.
		///</summary>
		[ImplementPropertyType("locationPhoto")]
		public string LocationPhoto
		{
			get { return this.GetPropertyValue<string>("locationPhoto"); }
		}

		///<summary>
		/// Location General Description: The brief location description located right underneath the location display name.
		///</summary>
		[ImplementPropertyType("locationTitleDescription")]
		public IHtmlString LocationTitleDescription
		{
			get { return this.GetPropertyValue<IHtmlString>("locationTitleDescription"); }
		}

		///<summary>
		/// Location Types
		///</summary>
		[ImplementPropertyType("locationTypes")]
		public IEnumerable<string> LocationTypes
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("locationTypes"); }
		}

		///<summary>
		/// Map File Upload
		///</summary>
		[ImplementPropertyType("mapFileUpload")]
		public IEnumerable<IPublishedContent> MapFileUpload
		{
			get { return this.GetPropertyValue<IEnumerable<IPublishedContent>>("mapFileUpload"); }
		}

		///<summary>
		/// MRI Description
		///</summary>
		[ImplementPropertyType("mriDescription")]
		public string MriDescription
		{
			get { return this.GetPropertyValue<string>("mriDescription"); }
		}

		///<summary>
		/// Optical Description
		///</summary>
		[ImplementPropertyType("opticalDescription")]
		public string OpticalDescription
		{
			get { return this.GetPropertyValue<string>("opticalDescription"); }
		}

		///<summary>
		/// Optical Hours
		///</summary>
		[ImplementPropertyType("opticalHours")]
		public IEnumerable<string> OpticalHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("opticalHours"); }
		}

		///<summary>
		/// Pharmacy Description
		///</summary>
		[ImplementPropertyType("pharmacyDescription")]
		public string PharmacyDescription
		{
			get { return this.GetPropertyValue<string>("pharmacyDescription"); }
		}

		///<summary>
		/// Pharmacy Hours
		///</summary>
		[ImplementPropertyType("pharmacyHours")]
		public IEnumerable<string> PharmacyHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("pharmacyHours"); }
		}

		///<summary>
		/// Phone Number
		///</summary>
		[ImplementPropertyType("phoneNumber")]
		public string PhoneNumber
		{
			get { return this.GetPropertyValue<string>("phoneNumber"); }
		}

		///<summary>
		/// Same Day Appointment Number
		///</summary>
		[ImplementPropertyType("sameDayAppointmentNumber")]
		public string SameDayAppointmentNumber
		{
			get { return this.GetPropertyValue<string>("sameDayAppointmentNumber"); }
		}

		///<summary>
		/// Services List: This is a bullet list of services to be displayed on the location page.
		///</summary>
		[ImplementPropertyType("servicesList")]
		public IEnumerable<string> ServicesList
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("servicesList"); }
		}

		///<summary>
		/// Toll Free Phone Number
		///</summary>
		[ImplementPropertyType("tollFreePhoneNumber")]
		public string TollFreePhoneNumber
		{
			get { return this.GetPropertyValue<string>("tollFreePhoneNumber"); }
		}

		///<summary>
		/// Hide from navigation
		///</summary>
		[ImplementPropertyType("umbracoNaviHide")]
		public bool UmbracoNaviHide
		{
			get { return this.GetPropertyValue<bool>("umbracoNaviHide"); }
		}

		///<summary>
		/// Urgent Care Description
		///</summary>
		[ImplementPropertyType("urgentCareDescription")]
		public string UrgentCareDescription
		{
			get { return this.GetPropertyValue<string>("urgentCareDescription"); }
		}

		///<summary>
		/// Urgent Care Hours
		///</summary>
		[ImplementPropertyType("urgentCareHours")]
		public IEnumerable<string> UrgentCareHours
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("urgentCareHours"); }
		}

		///<summary>
		/// Zip Code
		///</summary>
		[ImplementPropertyType("zipCode")]
		public string ZipCode
		{
			get { return this.GetPropertyValue<string>("zipCode"); }
		}
	}
}
