//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//
//    Umbraco.ModelsBuilder v3.0.7.99
//
//   Changes to this file will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq.Expressions;
using System.Web;
using Umbraco.Core.Models;
using Umbraco.Core.Models.PublishedContent;
using Umbraco.Web;
using Umbraco.ModelsBuilder;
using Umbraco.ModelsBuilder.Umbraco;

namespace Umbraco.Web.PublishedContentModels
{
	/// <summary>Provider</summary>
	[PublishedContentModel("provider")]
	public partial class Provider : PublishedContentModel
	{
#pragma warning disable 0109 // new is redundant
		public new const string ModelTypeAlias = "provider";
		public new const PublishedItemType ModelItemType = PublishedItemType.Content;
#pragma warning restore 0109

		public Provider(IPublishedContent content)
			: base(content)
		{ }

#pragma warning disable 0109 // new is redundant
		public new static PublishedContentType GetModelContentType()
		{
			return PublishedContentType.Get(ModelItemType, ModelTypeAlias);
		}
#pragma warning restore 0109

		public static PublishedPropertyType GetModelPropertyType<TValue>(Expression<Func<Provider, TValue>> selector)
		{
			return PublishedContentModelUtility.GetModelPropertyType(GetModelContentType(), selector);
		}

		///<summary>
		/// Academic Appointments
		///</summary>
		[ImplementPropertyType("academicAppointments")]
		public string AcademicAppointments
		{
			get { return this.GetPropertyValue<string>("academicAppointments"); }
		}

		///<summary>
		/// Also Sees Patients At
		///</summary>
		[ImplementPropertyType("alsoSeesPatientsAt")]
		public IEnumerable<string> AlsoSeesPatientsAt
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("alsoSeesPatientsAt"); }
		}

		///<summary>
		/// Bio
		///</summary>
		[ImplementPropertyType("bio")]
		public string Bio
		{
			get { return this.GetPropertyValue<string>("bio"); }
		}

		///<summary>
		/// Board Certifications
		///</summary>
		[ImplementPropertyType("boardCertifications")]
		public string BoardCertifications
		{
			get { return this.GetPropertyValue<string>("boardCertifications"); }
		}

		///<summary>
		/// Fellowship
		///</summary>
		[ImplementPropertyType("fellowship")]
		public string Fellowship
		{
			get { return this.GetPropertyValue<string>("fellowship"); }
		}

		///<summary>
		/// Image
		///</summary>
		[ImplementPropertyType("image")]
		public string Image
		{
			get { return this.GetPropertyValue<string>("image"); }
		}

		///<summary>
		/// Internship
		///</summary>
		[ImplementPropertyType("internship")]
		public string Internship
		{
			get { return this.GetPropertyValue<string>("internship"); }
		}

		///<summary>
		/// Main Location
		///</summary>
		[ImplementPropertyType("mainLocation")]
		public string MainLocation
		{
			get { return this.GetPropertyValue<string>("mainLocation"); }
		}

		///<summary>
		/// Medical School
		///</summary>
		[ImplementPropertyType("medicalSchool")]
		public string MedicalSchool
		{
			get { return this.GetPropertyValue<string>("medicalSchool"); }
		}

		///<summary>
		/// Phone
		///</summary>
		[ImplementPropertyType("phone")]
		public string Phone
		{
			get { return this.GetPropertyValue<string>("phone"); }
		}

		///<summary>
		/// Professional Societies
		///</summary>
		[ImplementPropertyType("professionalSocieties")]
		public string ProfessionalSocieties
		{
			get { return this.GetPropertyValue<string>("professionalSocieties"); }
		}

		///<summary>
		/// Quote
		///</summary>
		[ImplementPropertyType("quote")]
		public string Quote
		{
			get { return this.GetPropertyValue<string>("quote"); }
		}

		///<summary>
		/// Rating ID
		///</summary>
		[ImplementPropertyType("ratingID")]
		public string RatingID
		{
			get { return this.GetPropertyValue<string>("ratingID"); }
		}

		///<summary>
		/// Residency
		///</summary>
		[ImplementPropertyType("residency")]
		public string Residency
		{
			get { return this.GetPropertyValue<string>("residency"); }
		}

		///<summary>
		/// Specialties
		///</summary>
		[ImplementPropertyType("specialties")]
		public IEnumerable<string> Specialties
		{
			get { return this.GetPropertyValue<IEnumerable<string>>("specialties"); }
		}

		///<summary>
		/// State Licenses
		///</summary>
		[ImplementPropertyType("stateLicenses")]
		public string StateLicenses
		{
			get { return this.GetPropertyValue<string>("stateLicenses"); }
		}
	}
}
